[package]
name = "rpg"
version = "0.1.0"
edition = "2024"

[dependencies]
noise = "0.8"
rand = "0.8"
crossterm = "0.27"
ratatui = "0.26"
image = "0.24"
bevy = { version = "0.12", optional = true }

[features]
default = []
bevy-renderer = ["bevy"]
